---
- name: Adicionar hostnames
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ item.ip }} {{ item.hostname }}"
  with_items:
    - { ip: "{{ ip_controller }}", hostname: "{{ hostname_controller }}" }
    - { ip: "{{ ip_ansible }}", hostname: "{{ hostname_ansible }}" }
    - "{{ computes }}"
      
- name: Instalar chrony
  apt:
    name: chrony
    state: latest

- name: Adicionar '#' nas linhas que começam com 'pool' em /etc/chrony/chrony.conf
  lineinfile:
    path: /etc/chrony/chrony.conf
    line: '# {{item}}'
    regexp: "(^pool)"        
  with_items:
    - pool ntp.ubuntu.com        iburst maxsources 4
    - pool 0.ubuntu.pool.ntp.org iburst maxsources 1
    - pool 1.ubuntu.pool.ntp.org iburst maxsources 1
    - pool 2.ubuntu.pool.ntp.org iburst maxsources 2