---
- name: Instalacao de pacote MariaDB Server
  apt:
    name: mariadb-server
    state: latest

- name: Instalacao de pacote python3-pymysql
  apt:
    name: python3-pymysql
    state: latest

- name: Criar arquivo de configuração do banco de dados
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch          # cria arquivo

- name: Editar arquivo /etc/mysql/mariadb.conf.d/99-openstack.cnf
  lineinfile:
    dest: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: present
    line: "{{item}}"   # iteração sobre cada item no with_item
  with_items:
    - "[mysqld]"
    - bind-address = {{ip_controller}}
    - default-storage-engine = innodb
    - innodb_file_per_table = on
    - max_connections = 4096
    - collation-server = utf8_general_ci
    - character-set-server = utf8

- name: Reiniciar o serviço mysql
  service:    
    name: mysql
    state: restarted  # reiniciar serviço

# Realizando mysql_secure_installation  
- import_tasks: ../mysql-python_dependencies.yml

- name: Configurando "mysql_secure_installation" for Fresh MySQL Installation
  mysql_secure_installation:
    login_password: ''
    new_password: '{{MYSQL_PASS}}'
    user: root
    login_host: localhost
    hosts: ['localhost', '127.0.0.1', '::1']
    change_root_password: true
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
  register: secure

- debug:
    var: secure
    
# Used for testing.
- local_action: copy content={{secure}} dest=output.txt

# Message queue RabbitMq
- name: Instalar pacote Rabbitmq-server
  apt:
    name: rabbitmq-server
    state: latest
    
- name: Adicionar usuario openstack no Rabbitmq
  command: rabbitmqctl add_user openstack {{RABBIT_PASS}}
  ignore_errors: yes

- name: Permitir acesso de configuracao, leitura, e escrita openstack user
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

# Install/Config memcached
- name: Instalar memcached
  apt:
    name: memcached
    state: latest
    
- name: Instalar python3-memcache
  apt:
    name: python3-memcache
    state: latest

- name: Configurar arquivo /etc/memcached.conf
  lineinfile:
    path: /etc/memcached.conf
    line: '-l {{hostname_controller}}'
    regexp: "(^-l)"

- name: Reiniciar o serviço memcached
  service:    
    name: memcached
    state: restarted

# Install/config Etcd
- name: Instalar etcd
  apt:
    name: etcd
    state: latest

- name: Editar arquivo /etc/default/etc
  lineinfile:
    path: /etc/default/etcd
    state: present
    line: "{{item}}"
  with_items:
    - "#"
    - ETCD_NAME="{{hostname_controller}}"
    - ETCD_DATA_DIR="/var/lib/etcd"
    - ETCD_INITIAL_CLUSTER_STATE="new"
    - ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
    - ETCD_INITIAL_CLUSTER="{{hostname_controller}}=http://{{ip_controller}}:2380"
    - ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ip_controller}}:2380"
    - ETCD_ADVERTISE_CLIENT_URLS="http://{{ip_controller}}:2379"
    - ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
    - ETCD_LISTEN_CLIENT_URLS="http://{{ip_controller}}:2379"

- name: Habilitar servico etcd
  systemd:  
    name: etcd
    enabled: yes

- name: Reiniciar etcd
  systemd:
    name: etcd
    state: restarted