ansible_user: great
hostname_controller: "controller"
ip_controller: "192.168.0.102"
hostname_ansible: "ansible"
ip_ansible: "192.168.0.24"
ip_storage: "192.168.0.100"
subrede: "192.168.0.0/24"
ntp_server: "200.160.7.186"
name_nic_controller: "enp0s3"
name_nic_computes: "enp4s0"
ip_provider_network_controller: "192.168.0.102"
name_disc_storage: nvme0n1
name_disc_storage_part: nvme0n1p4
name_disc_conservar_so: nvme0n1

path_sql_socket: "/var/run/mysqld/mysqld.sock"                                                    # NORMALMENTE NÃO É NECESSÁRIO ALTERAR
nic: "{{ network_facts['ansible_facts']['ansible_' + name_nic_computes]['ipv4']['address'] }}"    # NÃO ALTERE

computes:
  - hostname: "compute1"
    ip: "192.168.0.100"
  - hostname: "compute2"
    ip: "192.168.0.101"