hostname_controller: "controller"
hostname_compute1: "compute1"
hostname_compute2: "compute2"
hostname_ansible: "ansible"
ip_controller: "192.168.0.123"
ip_compute1: "192.168.0.150"
ip_compute2: "192.168.0.102"
ip_storage: "192.168.0.150"
ip_ansible: "192.168.0.95"
subrede: "192.168.0.0/24"
ntp_server: "200.160.7.186"
path_sql_socket: "/var/run/mysqld/mysqld.sock"
name_nic_controller: "eth0"
name_nic_computes: "eno1"
ip_provider_network_controller: "192.168.0.123"
name_disc_storage: sda
name_disc_storage_part: sda4
name_disc_conservar_so: sda
nic: "{{ network_facts['ansible_facts']['ansible_' + name_nic_computes]['ipv4']['address'] }}"