
Vagrant.configure("2") do |config|

    # Selecionando box (imagem do SO)
    config.vm.box = "bento/ubuntu-22.04"
  
    # Atribundo hostnamame para a VM
    config.vm.hostname = "teste"
  
    # Criando uma rede privada, a VM receberá o IP 192.168.56.8
    config.vm.network "private_network", ip: "192.168.56.8"
 

    config.vbguest.auto_update = false
  
  end
  
