---
- name: Editar [agent] no /etc/neutron/plugins/ml2/openvswitch_agent.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    marker: "# {mark} start agent"
    insertafter: '^\[agent\]'
    block: |
      tunnel_types = vxlan
      prevent_arp_spoofing = True

- name: Editar [ovs] no /etc/neutron/plugins/ml2/openvswitch_agent.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    marker: "# {mark} start ovs"
    insertafter: '^\[ovs\]'
    block: |
      local_ip = {{ ip_controller }}

- name: Editar arquivo /etc/neutron/dhcp_agent.ini
  lineinfile:
    path: /etc/neutron/dhcp_agent.ini
    regexp: '^#dnsmasq_config_file ='
    line: 'dnsmasq_config_file = /etc/neutron/dnsmasq-neutron.conf'

- name: Criar arquivo /etc/neutron/dnsmasq-neutron.conf
  file:
    path: /etc/neutron/dnsmasq-neutron.conf
    state: touch          # cria arquivo

- name: Editar arquivo /etc/neutron/dnsmasq-neutron.conf
  lineinfile:
    dest: /etc/neutron/dnsmasq-neutron.conf
    state: present
    line: "dhcp-option-force=26,1450" 

- name: Alterar dono e grupo do arquivo /etc/neutron/dnsmasq-neutron.conf
  file:
    path: /etc/neutron/dnsmasq-neutron.conf
    owner: root
    group: neutron