---
- name: Editar [ml2] (tenant_network_types) no arquivo /etc/neutron/plugins/ml2/ml2_conf.ini
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: '^#tenant_network_types'
    line: 'tenant_network_types = vxlan'

- name: Editar [ml2_type_flat] (flat_newtworks) no arquivo /etc/neutron/plugins/ml2/ml2_conf.ini
  lineinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: '^#flat_networks'
    line: 'flat_networks = *'

- name: Editar [ml2_type_vxlan] (vni_ranges) no arquivo /etc/neutron/plugins/ml2/ml2_conf.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/ml2_conf.ini
    marker: "# {mark} start ml2_type_vxlan"
    insertafter: '^\[ml2_type_vxlan\]'
    block: |
      vni_ranges = 1:1000

- name: Editar [agent] no /etc/neutron/plugins/ml2/openvswitch_agent.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    marker: "# {mark} start agent"
    insertafter: '^\[agent\]'
    block: |
      tunnel_types = vxlan
      prevent_arp_spoofing = True

- name: Editar [ovs] no /etc/neutron/plugins/ml2/openvswitch_agent.ini
  blockinfile:
    path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    marker: "# {mark} start ovs"
    insertafter: '^\[ovs\]'
    block: |
      local_ip = {{ nic }}