---
- name: Aguardar 30 segundos antes de executar a próxima tarefa
  pause:
    seconds: 60

- name: Adicionar nós de computacao a database
  command: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
  register: result_addnodes

- debug:
    var: result_addnodes.stdout_lines