---
- name: Configuração OpenVSwtich Controller
  hosts: controller

  user: great
  become: yes

  vars_files:
   - vars/main.yaml

  tasks:
    - name: Adicionar interface virtual OpenVSwitch
      command: ovs-vsctl add-br br-provider
  
    - name: Editar no arquivo /etc/neutron/plugins/ml2/openvswitch_agent.ini
      lineinfile:
        path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
        regexp: '^bridge_mappings'
        line: 'bridge_mappings = provider:br-provider'
  
    - name: Editar no arquivo /etc/neutron/plugins/ml2/ml2_conf.ini
      lineinfile:
        path: /etc/neutron/plugins/ml2/ml2_conf.ini
        regexp: '^flat_networks'
        line: 'flat_networks = *'
  
    - name: Trocar interfaces no arquivo /etc/netplan/00-installer-config.yaml
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        regexp: '{{ name_nic_controller }}'
        line: '    br-provider:'

    - name: Adicionar interface física com indentação correta
      blockinfile:
        path: /etc/netplan/00-installer-config.yaml
        marker: "# {mark} start add interface fisica"
        insertafter: '^ *ethernets:'  # Adiciona após "ethernets"
        block: |
            {{ ' ' * 4 }}{{ name_nic_controller }}:
            {{ ' ' * 6 }}dhcp4: no
    
    - name: Associar interface virtual OpenVSwitch ao inteface Fisica e aplicar
      command: nohup bash -c "ovs-vsctl add-port br-provider eth0 && netplan apply" > /tmp/command.log 2>&1 &
      ignore_errors: yes


- name: Configuração OpenVSwtich Computes
  hosts: computes

  user: great
  become: yes

  vars_files:
   - vars/main.yaml

  tasks:
    - name: Adicionar interface virtual OpenVSwitch
      command: ovs-vsctl add-br br-provider
  
    - name: Editar no arquivo /etc/neutron/plugins/ml2/openvswitch_agent.ini
      lineinfile:
        path: /etc/neutron/plugins/ml2/openvswitch_agent.ini
        regexp: '^bridge_mappings'
        line: 'bridge_mappings = provider:br-provider'
  
    - name: Editar no arquivo /etc/neutron/plugins/ml2/ml2_conf.ini
      lineinfile:
        path: /etc/neutron/plugins/ml2/ml2_conf.ini
        regexp: '^flat_networks'
        line: 'flat_networks = *'
  
    - name: Trocar interfaces no arquivo /etc/netplan/00-installer-config.yaml
      lineinfile:
        path: /etc/netplan/00-installer-config.yaml
        regexp: '{{ name_nic_controller }}'
        line: '    br-provider:'

    - name: Adicionar interface física com indentação correta
      blockinfile:
        path: /etc/netplan/00-installer-config.yaml
        marker: "# {mark} start add interface fisica"
        insertafter: '^ *ethernets:'  # Adiciona após "ethernets"
        block: |
            {{ ' ' * 4 }}{{ name_nic_controller }}:
            {{ ' ' * 6 }}dhcp4: no
    
    - name: Associar interface virtual OpenVSwitch ao inteface Fisica e aplicar
      command: nohup bash -c "ovs-vsctl add-port br-provider eth0 && netplan apply" > /tmp/command.log 2>&1 &
      ignore_errors: yes



